// <auto-generated />
using System;
using DevOpsPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevOpsPortal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911230037_Phase13b_EnvironmentPrimaryTargetServer")]
    partial class Phase13b_EnvironmentPrimaryTargetServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.AllowedDeploymentRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TargetServerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetServerId", "RootPath")
                        .IsUnique();

                    b.ToTable("AllowedDeploymentRoots");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.ApplicationEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUrl")
                        .HasColumnType("text");

                    b.Property<int?>("BackupRetentionCount")
                        .HasColumnType("integer");

                    b.Property<string>("BackupSubPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .HasColumnType("text");

                    b.Property<string>("ComposeFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComposeProjectName")
                        .HasColumnType("text");

                    b.Property<string>("ContainerName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentRootPath")
                        .HasColumnType("text");

                    b.Property<Guid>("EnvironmentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalNetworkName")
                        .HasColumnType("text");

                    b.Property<string>("HealthCheckEndpoint")
                        .HasColumnType("text");

                    b.Property<int>("HealthCheckIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("HealthCheckTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("HealthCheckType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PublishSubPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<Guid>("TargetServerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseDownWithVolumesOnDeploy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentDefinitionId");

                    b.HasIndex("TargetServerId");

                    b.HasIndex("ApplicationId", "EnvironmentDefinitionId")
                        .IsUnique();

                    b.ToTable("ApplicationEnvironments");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.BuildConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildServerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DockerfilePath")
                        .HasColumnType("text");

                    b.Property<string>("ImageRegistry")
                        .HasColumnType("text");

                    b.Property<string>("ImageRepository")
                        .HasColumnType("text");

                    b.Property<int>("ImageTagStrategy")
                        .HasColumnType("integer");

                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<string>("ProjectOrSolutionPath")
                        .HasColumnType("text");

                    b.Property<string>("PublishArguments")
                        .HasColumnType("text");

                    b.Property<string>("PublishConfiguration")
                        .HasColumnType("text");

                    b.Property<string>("SdkVersion")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("BuildServerId");

                    b.ToTable("BuildConfigurations");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.BuildRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<int?>("BuildNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("BuildServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuildUrl")
                        .HasColumnType("text");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProviderQueueItemId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestedSemVer")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildServerId");

                    b.HasIndex("ApplicationId", "RequestedAt");

                    b.ToTable("BuildRequests");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.BuildServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiTokenEnvVarName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BuildServers");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("CommitAuthor")
                        .HasColumnType("text");

                    b.Property<string>("CommitMessage")
                        .HasColumnType("text");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnvironmentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("HealthCheckDetail")
                        .HasColumnType("text");

                    b.Property<bool?>("HealthCheckPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageReference")
                        .HasColumnType("text");

                    b.Property<bool>("IsRollback")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PromotionRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RollbackOfDeploymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VersionLabel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationEnvironmentId");

                    b.HasIndex("EnvironmentDefinitionId");

                    b.HasIndex("PromotionRequestId");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("RollbackOfDeploymentId");

                    b.HasIndex("ApplicationId", "EnvironmentDefinitionId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (0,1,2)");

                    b.HasIndex("ApplicationId", "EnvironmentDefinitionId", "CommitSha");

                    b.HasIndex("ApplicationId", "EnvironmentDefinitionId", "Status");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.DeploymentLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId", "Sequence")
                        .IsUnique();

                    b.ToTable("DeploymentLogEntries");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.EnvironmentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProductionLike")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("PrimaryTargetServerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PrimaryTargetServerId");

                    b.ToTable("EnvironmentDefinitions");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.ManagedApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeploymentMode")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourcePath")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.ProductionApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalTokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationRecipients")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PromotionRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalTokenHash")
                        .IsUnique();

                    b.HasIndex("PromotionRequestId")
                        .IsUnique();

                    b.ToTable("ProductionApprovals");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.PromotionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ApprovalTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovalTokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BranchPromotionDetail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("BranchPromotionSucceeded")
                        .HasColumnType("boolean");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionNotes")
                        .HasColumnType("text");

                    b.Property<string>("FromBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FromEnvironmentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotificationRecipients")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceDeploymentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ToBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ToEnvironmentDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalTokenHash")
                        .IsUnique();

                    b.HasIndex("FromEnvironmentDefinitionId");

                    b.HasIndex("SourceDeploymentId");

                    b.HasIndex("ToEnvironmentDefinitionId");

                    b.HasIndex("ApplicationId", "ToEnvironmentDefinitionId", "Status");

                    b.ToTable("PromotionRequests");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("BuildRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("BuildStatus")
                        .HasColumnType("integer");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("BuildRequestId")
                        .IsUnique();

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenEnvVarName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccessTokenStoreKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.SecretReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EnvironmentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Host")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("StoreKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentDefinitionId");

                    b.HasIndex("ApplicationId", "EnvironmentDefinitionId");

                    b.ToTable("SecretReferences");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.SecretValueRecord", b =>
                {
                    b.Property<string>("StoreKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoreKey");

                    b.ToTable("SecretValues");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.TargetServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SshAuthMethod")
                        .HasColumnType("integer");

                    b.Property<string>("SshCredentialStoreKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SshPassphraseStoreKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SshPort")
                        .HasColumnType("integer");

                    b.Property<string>("SshUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TargetServers");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanApproveProduction")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.UserEnvironmentAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvironmentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentDefinitionId");

                    b.HasIndex("UserId", "EnvironmentDefinitionId")
                        .IsUnique();

                    b.ToTable("UserEnvironmentAccess");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.AllowedDeploymentRoot", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.TargetServer", "TargetServer")
                        .WithMany("AllowedDeploymentRoots")
                        .HasForeignKey("TargetServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetServer");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.ApplicationEnvironment", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.ManagedApplication", "Application")
                        .WithMany("Environments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.EnvironmentDefinition", "EnvironmentDefinition")
                        .WithMany()
                        .HasForeignKey("EnvironmentDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.TargetServer", "TargetServer")
                        .WithMany()
                        .HasForeignKey("TargetServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("EnvironmentDefinition");

                    b.Navigation("TargetServer");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.BuildConfiguration", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.ManagedApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.BuildServer", "BuildServer")
                        .WithMany()
                        .HasForeignKey("BuildServerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("BuildServer");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.BuildRequest", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.ManagedApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.BuildServer", "BuildServer")
                        .WithMany()
                        .HasForeignKey("BuildServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("BuildServer");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.Deployment", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.ApplicationEnvironment", "ApplicationEnvironment")
                        .WithMany()
                        .HasForeignKey("ApplicationEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.ManagedApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.EnvironmentDefinition", "EnvironmentDefinition")
                        .WithMany()
                        .HasForeignKey("EnvironmentDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.PromotionRequest", "PromotionRequest")
                        .WithMany()
                        .HasForeignKey("PromotionRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevOpsPortal.Domain.Entities.Release", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevOpsPortal.Domain.Entities.Deployment", "RollbackOfDeployment")
                        .WithMany()
                        .HasForeignKey("RollbackOfDeploymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("ApplicationEnvironment");

                    b.Navigation("EnvironmentDefinition");

                    b.Navigation("PromotionRequest");

                    b.Navigation("Release");

                    b.Navigation("RollbackOfDeployment");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.DeploymentLogEntry", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.Deployment", "Deployment")
                        .WithMany("LogEntries")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.EnvironmentDefinition", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.TargetServer", "PrimaryTargetServer")
                        .WithMany()
                        .HasForeignKey("PrimaryTargetServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrimaryTargetServer");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.ManagedApplication", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.ProductionApproval", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.PromotionRequest", "PromotionRequest")
                        .WithOne("ProductionApproval")
                        .HasForeignKey("DevOpsPortal.Domain.Entities.ProductionApproval", "PromotionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromotionRequest");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.PromotionRequest", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.ManagedApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.EnvironmentDefinition", "FromEnvironmentDefinition")
                        .WithMany()
                        .HasForeignKey("FromEnvironmentDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.Deployment", "SourceDeployment")
                        .WithMany()
                        .HasForeignKey("SourceDeploymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.EnvironmentDefinition", "ToEnvironmentDefinition")
                        .WithMany()
                        .HasForeignKey("ToEnvironmentDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("FromEnvironmentDefinition");

                    b.Navigation("SourceDeployment");

                    b.Navigation("ToEnvironmentDefinition");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.Release", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.ManagedApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.BuildRequest", "BuildRequest")
                        .WithOne("Release")
                        .HasForeignKey("DevOpsPortal.Domain.Entities.Release", "BuildRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("BuildRequest");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.SecretReference", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.ManagedApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevOpsPortal.Domain.Entities.EnvironmentDefinition", "EnvironmentDefinition")
                        .WithMany()
                        .HasForeignKey("EnvironmentDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("EnvironmentDefinition");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.UserEnvironmentAccess", b =>
                {
                    b.HasOne("DevOpsPortal.Domain.Entities.EnvironmentDefinition", "EnvironmentDefinition")
                        .WithMany()
                        .HasForeignKey("EnvironmentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevOpsPortal.Domain.Entities.User", "User")
                        .WithMany("EnvironmentAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvironmentDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.BuildRequest", b =>
                {
                    b.Navigation("Release");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.Deployment", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.ManagedApplication", b =>
                {
                    b.Navigation("Environments");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.PromotionRequest", b =>
                {
                    b.Navigation("ProductionApproval");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.TargetServer", b =>
                {
                    b.Navigation("AllowedDeploymentRoots");
                });

            modelBuilder.Entity("DevOpsPortal.Domain.Entities.User", b =>
                {
                    b.Navigation("EnvironmentAccess");
                });
#pragma warning restore 612, 618
        }
    }
}
